services:
  directus:
    image: directus/directus:latest

    ports:
      - "8056:8055"

    environment:
      KEY: "mysecretkey"
      SECRET: "mysecret"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"

      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "/directus/uploads"

    volumes:
      - ./database:/directus/database
      - directus_uploads:/directus/uploads
      - ./extensions:/directus/extensions

volumes:
  directus_uploads: