services:
  directus:
    image: directus/directus:latest

    ports:
      - "8056:8055"

    environment:
      KEY: "mysecretkey"
      SECRET: "mysecret"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"

      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/tmp/directus.db"

    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions